flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/rarecoal.git
    commit: 10de1382bcf0600682357f573fdc07aac4fc8a88
# extra-deps:
# - cabal-helper-0.6.3.1
resolver: lts-7.0
