flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: f4008deeae891b41091a08eadcbcd6c6f9b8a469
  extra-dep: true
resolver: lts-10.5
extra-deps:
    - parsec3-numbers-0.1.0
